### ISSUE TITLE
swagger 초기 세팅

### ISSUE THREAD

**Issue by Gnu-Kenny** [h-jjang/bauction#10]
API 문서화와 API Test를 위해 Swagger 초기 세팅 진행

- [x]  Graddle 추가하기
- [x] Spring Security Swagger Ignore 설정
- [x] MVC Path Match 전략 변경하기

**Comment by Gnu-Kenny** [comment]
Graddle에 springfox-spring-web 2.9.2 버전에 취약점이 있음을 확인했습니다. 그리고
3.0.0 버전이 하위 버전들을 호환하는 것을 확인하여 3.0.0 버전을 채택했습니다.

Reference
[About Vulnerabilities](https://mvnrepository.com/artifact/io.springfox/springfox-spring-web/2.9.2)
[About Defendency](https://github.com/springfox/springfox/issues/3386)

**Comment by kim1387** [comment]
spring 2.6.부터는 기본 전략이 mvcMatchers 전략이 변경 되어 spring security에서 web.ignore로  swagger 설정하기 위해서는 spring.mvc.pathmatch.matching-strategy 전략을 ant-path-matcher로 바꿔줘야한다.

https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.6-Release-Notes

If you are using Spring Security, you should review your use of mvcMatchers to ensure that your matchers continue to meet your needs. With AntPathMatcher, authorizeRequests.mvcMatchers("hello").permitAll() would grant access to /hello. The more precise matching of PathPatternParser requires the use of authorizeRequests.mvcMatchers("/hello").permitAll() (note the leading /) instead.

If you need to switch the default back to AntPathMatcher, you can set spring.mvc.pathmatch.matching-strategy to ant-path-matcher.

```yaml
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
```

**Comment by Gnu-Kenny** [comment]
의존성 주입에서 implementation 'org.springframework.boot:spring-boot-starter-actuator'과
springfox 와의 충돌을 확인
-> org.springdoc:springdoc-openapi-ui:1.6.6 사용해서 해결
[springdoc.org](https://springdoc.org/#demos)
