### ISSUE TITLE
jpa 저장 테스트 관련 에러에 대한 질문

### ISSUE THREAD

**Issue by 0BVer** [h-jjang/bauction#32]
```
@ExtendWith(MockitoExtension.class)
class ImageTest {
    @Mock
    private ImageRepository imageRepository;

    @Test
    void ImageTest() throws JsonProcessingException {
        //given
        Image image = new Image(0L, "test path", false);
        Image image1 = imageRepository.save(image);
        Long imageId = image1.getId();

        //when
        Optional<Image> image2 = imageRepository.findById(imageId);

        //then1
        Assertions.assertEquals(image2, image1);

        //then2
        image.removeImage();
        Assertions.assertEquals(image2.get().getPath(), "test path");
        Assertions.assertEquals(image2.get().getRemoved(), true);
    }
}
```

<img width="1102" alt="스크린샷 2022-04-18 오후 3 39 07" src="https://user-images.githubusercontent.com/73998876/163766588-58c7f87f-a031-4c1c-a6dc-244a36831e98.png">

이미지 엔티티를 imageRepository에 저장을 하고 불러오는 테스트를 작성하고 있었습니다.

현재 체크한 바로는 이미지 리포지토리에 이미지 객체가 저장이 되지 않는것 같습니다.

`image1 `이 null이고, `save()`를 한 상태에서 `findAll()`을 해도 null이 뜹니다.

혹시 spring data jpa를 테스트 할 때 다른 방식으로 접근을 해서 사용해야 하는건가요?

**Comment by kim1387** [comment]
repository test를 하고  싶으신건가요??

**Comment by 0BVer** [comment]
넵

**Comment by kim1387** [comment]
그럴땐 mock을 사용하는 것보다 @DataJpaTest를 클래스위에 붙여서 사용하고 
repository는 @ Autowired를 사용하여 직접 테스트 해보는 것이 좋아보이네요!
클래스명도 ImageRepositoryTest라고 바꾸면 클래스명만 보고 무엇을 테스트하는지 조금더 알기 쉬울 것 같습니다!

`   

    @Autowired
    CustomerRepository customerRepository;

    @Mock
    PasswordEncoder passwordEncoder;

    @Test
    void save() {
        CustomerDto customerDto = CustomerDto
                .builder()
                .name("JAVA")
                .email("email@gmail.com")
                .token("JAVATOKEN")
                .build();
        Customer customer = customerDto.toEntity(passwordEncoder);
        customerRepository.save(customer);
        Customer findCustomer = customerRepository.findCustomerById(customer.getId()).orElseThrow(EntityNotFoundException::new);
        assertEquals(findCustomer.getName(),customer.getName());
    }
`

**Comment by 0BVer** [comment]
아하 감사합니다!

**Comment by 0BVer** [comment]
`@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)`
@kim1387 혹시 이 어노테이션도 설정을 해주어야 하는건가요?

**Comment by kim1387** [comment]
앗 아닙니다 무시하셔도 되는 설정입니다! test db를 h2로 변경할려고 썼던 어노테이션인데 필요가 없습니다!

**Comment by kim1387** [comment]
> `@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)` @kim1387 혹시 이 어노테이션도 설정을 해주어야 하는건가요?
앗 아닙니다 무시하셔도 되는 설정입니다! test db를 h2로 변경할려고 썼던 어노테이션인데 필요가 없습니다!
