### ISSUE TITLE
slf4j log 구현체 선택 log4j vs logback vs log4j2

### ISSUE THREAD

**Issue by kim1387** [h-jjang/bauction#35]
slf4j의 구현체로 log4j vs logback vs log4j2중 어느 것을 골라야 할까?

![image](https://user-images.githubusercontent.com/58874807/165495257-23341097-2b54-4380-86fc-d26b4273969d.png)
# logging 벤치마킹 결과 log4j2가 압도적인 성능을 자랑하므로 log4j2를 채택하는건 어떨까요? #

log4j
일단 전통이 깊은 가장 오래된 방식이며 현재는 지원을 하지 않고 slf4j를 지원하지 않는다. 
slf4j를 지원하지 않음으로 사용이 어렵다.

logback
log4j의 후속작으로 log4j의 문제점을 개선하여 나오게 되었고 spring에서 default로 채택하고 있는 중이다.

log4j2
logback의 구조적 한계를 개선하기 위해 나온 최신 로그 구현체로
[공식문서](https://logging.apache.org/log4j/2.x/performance.html)에 따르면 비동기 로깅이 가능하여 성능은 logback보다 18배 정도 빠르며 latancy는 수십 배 빠르다고 나와있다.

**Comment by kim1387** [comment]
추가 logging을 할 때 비동기 로깅을 하는 것이 성능적으로 유리하다는 것을 벤치마킹 표를 보면 알 수 있는데 

 [AsyncAppender](https://logging.apache.org/log4j/log4j-2.4/manual/appenders.html) 공식문서에 의하면 kafka와 같은 다양한 appender를 제공하는데 이는 확장성에도 유리하다고 생각됩니다.

나중에 kafka로 log수집을 같이 관리 해보면 좋은 경험이 될 것 같습니다!

**Comment by 0BVer** [comment]
좋습니다 성능좋은게 최고죠
