### ISSUE TITLE
post 엔티티가 image_id를 가지고 있습니다

### ISSUE THREAD

**Issue by 0BVer** [h-jjang/bauction#46]
[DB 설계 페이지](https://ce19f003.notion.site/DB-Table-6aa1ec1892724595919cca90b0d70b8f) 보면 아래 사진처럼 image_id가 post에 들어있는데 Image 엔티티가 post_id를 가지도록 변경하는게 좋다고 생각하는데 어떻게 생각하시나요? 
현재의 구조라면 post 하나당 하나의 이미지만을 갖게 되는 구조라서 변경이 필요하다고 생각합니다.
<img width="943" alt="스크린샷 2022-05-04 오후 5 34 41" src="https://user-images.githubusercontent.com/73998876/166647761-25c6b936-4a11-4388-b974-999a729b5433.png">
 @kim1387 @Gnu-Kenny @Yunkeun

**Comment by Gnu-Kenny** [comment]
image 테이블에 target_id가 존재하니 post 내부 image_id 만 삭제해주면 될 것 같습니다!
하지만 추후에 동네 생활, 매물 게시글, 댓글에 같이 쓰이기 위해 설계한 Image 테이블의 설계가 올바른지는 한번 더 얘기 해보면 좋을 것 같습니다.
