### ISSUE TITLE
스프링부트 다운그레이드 필요

### ISSUE THREAD

**Issue by Yunkeun** [h-jjang/bauction#48]
어제 말씀드린 Spring Data JPA의 Containing 에러 관해서 원인과 해결법을 찾았습니다.

원인은 hibernate 최신 버전에서 발생한 에러이며 스프링부트 2.6.5 버전에서 최신 hibernate가 사용되는데 최신 hibernate에서 발생한 버그로 추정됩니다.
해결법은 스프링부트 다운그레이드입니다.
2.6.4로 변경 후 실행해보니 해결했습니다.
관련해서 [블로그](https://yoonveloping.tistory.com/49)에 정리했고 
spring-data-jpa에 나름 최신에 [issue](https://github.com/spring-projects/spring-data-jpa/issues/2472)로 올라왔네요!

혹시 스프링부트 버전 변경 시 그에 따른 수정 사항이 많아진다면 조금 더 고려해봐도 좋을 것 같고
크게 문제가 되지 않는다면 2.6.4 버전으로 다운그레이드 하면 검색 성능 향상에 도움이 될 것 같습니다.

**Comment by kim1387** [comment]
오호,.. 찾느라 고생하셨네요,, 좋은 방법인것 같습니다!
