### ISSUE TITLE
Post 엔티티 관련 질문

### ISSUE THREAD

**Issue by Yunkeun** [h-jjang/bauction#52]
- 게시글 등록 시간 추가해야할 것 같습니다.
    - 게시 시간 순서로 정렬하려고 합니다.
- is_sale_completion → isSaleCompletion
    - 스네이크 케이스로 하신 이유가 있는지 궁금합니다.
    - 없다면, 스네이크 케이스 → 카멜 케이스로 변경하는게 좋을 것 같습니다.
    - 설정을 변경하면 될 것 같긴 한데, 스네이크 케이스는 JPA에서 못잡네요.
- isSaleCompletion
    - 현재 ‘false’, ‘true’로 필터 구현했습니다. 추후 enum 으로 변경 시 변경하겠습니다.
    - SALE("판매중"), RESERVED("예약중"), SOLD("판매완료")
    - 설계 테이블에는 "판매 대기"로 적혀있는데 위의 세 개가 더 바람직하다고 생각합니다. 의견 주세요!

**Comment by 0BVer** [comment]
저 부분 코딩할 때 카멜 케이스여도 Jpa가 자동으로 스네이크 케이스로 변환하는걸 모르고 있어서 스네이크 케이스로 작성했었습니다. 다른 부분은 변경 진행하주시면 Dto 반영하겠습니다

**Comment by Yunkeun** [comment]
제가 Post 쪽도 수정할까요? 아니면 수정됐다 치고 진행할까요?

**Comment by 0BVer** [comment]
제가 수정하겠습니다. 수정된걸로 생각하고 진행해 주세요
