### ISSUE TITLE
개발 환경 구성 - 도커

### ISSUE THREAD

**Issue by 0BVer** [h-jjang/bauction#7]
# 도커 환경 구성

- [ ] 최소 개발을 위한 docker-compose.yml 파일 작성

- springboot 

- mysql 

- react 

- redis  

(우측의 Development 에서 branch 생성 후 작업 하시면 됩니다. 완료 후 풀 리퀘스트 요청하시고, 한 명에게 코드 리뷰 후 머지 하시면 됩니다.)

**Comment by 0BVer** [comment]
https://github.com/0BVer/spring-react-docker
오늘 만들어봤던건데 프론트엔드쪽 참고해 보시면 될거같아요

**Comment by Yunkeun** [comment]
frontend volumes 설정 관련 오류였네요,
참고해서 수정했고 곧 PR 쏘겠습니다.
